// Generated by CoffeeScript 1.10.0
function(eventCollection) {
  var amp, document, documentIdleEvent, href, location, text;
  documentIdleEvent = eventCollection.documentIdleEvent();
  while (!documentIdleEvent) {
    return null;
  }
  location = documentIdleEvent.location, document = documentIdleEvent.document;
  amp = document.querySelector('link[rel=amphtml]');
  if (amp) {
    href = amp.getAttribute('href');
    text = "amp: ${href}";
  }
  console.log(amp);
  return this.createResult(1, 'HEAD', text, 'info');
}
